[package]
name = "my_second_blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
# Add necessary dependencies to your Cargo.toml file (for hashing and serialization): 
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.0"
hex = "0.4.3"
